version: '3.4'

services:
  pattr-frontend:
    image: brycemclachlan/pattr-frontend:production
    build:
      context: services/frontend/service
      dockerfile: ./Dockerfile
    ports:
      - 80:3001
  reset-db:
    restart: always
    image: brycemclachlan/pattr-resetdb:production
    build:
      context: services/reset-db/service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - db.secret.env
    ports:
      - 3002:3000
  graphql-engine:
    restart: always
    image: hasura/graphql-engine:v2.0.0-alpha.5
    ports:
      - 8080:8080
    depends_on:
      - 'postgres'
    env_file:
      - db.secret.env
      - hasura.secret.env
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - db.secret.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
