version: '3.4'

services:
  pattrbackend:
    image: pattrbackend
    build:
      context: service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
