apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pattr
resources:
  - graphql-engine-deployment.yaml
  - graphql-engine-ingress.yaml
  - graphql-engine-service.yaml
  - pattr-frontend-deployment.yaml
  - pattr-frontend-ingress.yaml
  - pattr-frontend-service.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-volume-persistentvolumeclaim.yaml
  - reset-db-deployment.yaml
  - pattr-namespace.yaml
  - db-secret-env-configmap.yaml
  - hasura-secret-env-configmap.yaml
