apiVersion: v1
kind: Service
metadata:
  labels:
    service: pattr-frontend
  name: pattr-frontend
spec:
  ports:
    - name: '3001'
      port: 3001
      targetPort: 3001
  selector:
    service: pattr-frontend
