apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: postgres-volume
  name: postgres-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
