#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx prettier --single-quote --write **/*.js
npx standard --fix --env jest
find ./*/ -name "package.json" ! -path "*/node_modules/*" -execdir npm test -- --watchAll=false \;

(git --no-pager diff --name-only --cached | while read line || [[ -n $line ]];
do
  git add $line
done)  > /dev/null 2>&1
